Minor fixes into generate mesh hierarchy
gridap/GridapP4est.jl pull request #19
Opened 2022-08-01 07:39 UTC by principejavier

@amartinhuertas have a look to the changes to mpi tests, I only added an if statement but did not change the indentation (to keep the small change easily visible), I don't know what's the poilcy in these cases...

2022-08-01 07:50 UTC, amartinhuertas commented
Ok, thanks! I have changed the base branch.

2022-08-01 07:55 UTC, amartinhuertas commented on test/GMG/mpi/GMGLinearSolversPoissonTests.jl
> +    if GridapP4est.i_am_in(mh.level_parts[1])
Wouldnt it be better to handle this at the library level (if possible) instead of transferring the responsibility to the user driver?

2022-08-01 07:56 UTC, amartinhuertas commented on test/GMG/mpi/RedistributeToolsTests.jl
> +    if GridapP4est.i_am_in(mh.level_parts[1])
see https://github.com/gridap/GridapP4est.jl/pull/19/files#r934239967

2022-08-01 07:56 UTC, amartinhuertas requested changes
Hi @principejavier ! Thanks for your work. I have commented the current changes towards potential improvements.

2022-08-02 13:45 UTC, principejavier commented
Hi @amartinhuertas ! Have a look to the simple modification of prun (and tests). I think this is what we discussed, is it?

2022-08-04 08:55 UTC, amartinhuertas commented
> Hi @amartinhuertas ! Have a look to the simple modification of prun (and tests). I think this is what we discussed, is it?

Yes. Thanks for your work.

2022-08-04 08:56 UTC, amartinhuertas approved these changes

2022-08-04 10:00 UTC, merged